addons:
  ssh_known_hosts: kabi.tech
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e74b5ba78624_key -iv $encrypted_e74b5ba78624_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
